const Homeproduct =
[
    {
        Id: 1,
        Name: "product1",
        price: "26",
        image: "image/p1.webp",
        cat: "tv",
        type: "new",
    },
    {
        Id: 2,
        Name: "product2",
        price: "96",
        image: "image/p2.webp",
        cat: "laptop",
        type: "new",
    },
    {
        Id: 3,
        Name: "product3",
        price: "36",
        image: "image/p3.webp",
        cat: "watch",
        type: "new",
    },
    {
        Id: 4,
        Name: "product4",
        price: "636",
        image: "image/p9.jpg",
        cat: "laptop",
        type: "new",
    },
    {
        Id: 5,
        Name: "product5",
        price: "46",
        image: "image/p4.webp",
        cat: "speaker",
        type: "featured",
    },
    {
        Id: 6,
        Name: "product6",
        price: "56",
        image: "image/p5.webp",
        cat: "elecktrpnics",
        type: "featured",
    },
    {
        Id: 7,
        Name: "product7",
        price: "956",
        image: "image/p10.jpg",
        cat: "headphone",
        type: "featured",
    },
    {
        Id: 8,
        Name: "product8",
        price: "389",
        image: "image/p11.jpg",
        cat: "elecktrpnics",
        type: "featured",
    },
    {
        Id: 9,
        Name: "product9",
        price: "67",
        image: "image/p6.webp",
        cat: "phone",
        type: "top",
    },    {
        Id: 10,
        Name: "product10",
        price: "76",
        image: "image/p7.webp",
        cat: "speaker",
        type: "top",
    },    
    {
        Id: 11,
        Name: "product11",
        price: "28",
        image: "image/p8.webp",
        cat: "speaker",
        type: "top",
    },
    {
        Id: 12,
        Name: "product12",
        price: "807",
        image: "image/p12.jpg",
        cat: "speaker",
        type: "top",
    },
    {
        Id: 14,
        Name: "product14",
        price: "807",
        image: "S-tv-img.jpg",
        cat: "shop",
        type: "slider",
        info: "If you're in the market for a new TV, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them. Lastly, if the price fits your budget, it might be the right choice.",
    },
    {
        Id: 15,
        Name: "product14",
        price: "807",
        image: "S-tv-img.jpg",
        cat: "cart",
        type: "slider",
        info: "If you're in the market for a new TV, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them. Lastly, if the price fits your budget, it might be the right choice.",
    }
    
    
]
export default Homeproduct;