const Homeproduct =
[
    {
        Id: 1,
        Name: "product1",
        price: "26",
        image: "image/p1.webp",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 2,
        Name: "product2",
        price: "96",
        image: "image/p2.webp",
        cat: "laptop",
        type: "new",
        color: "red",
    },
    {
        Id: 3,
        Name: "product3",
        price: "36",
        image: "image/p3.webp",
        cat: "watch",
        type: "new",
        color: "red",
    },
    {
        Id: 4,
        Name: "product4",
        price: "636",
        image: "image/p9.jpg",
        cat: "laptop",
        type: "new",
        color: "red",
    },
    {
        Id: 5,
        Name: "product5",
        price: "46",
        image: "image/p4.webp",
        cat: "speaker",
        type: "featured",
        color: "black",
    },
    {
        Id: 6,
        Name: "product6",
        price: "56",
        image: "image/p5.webp",
        cat: "elecktrpnics",
        type: "featured",
        color: "black",
    },
    {
        Id: 7,
        Name: "product7",
        price: "956",
        image: "image/p10.jpg",
        cat: "headphones",
        type: "featured",
        color: "black",
    },
    {
        Id: 8,
        Name: "product8",
        price: "389",
        image: "image/p11.jpg",
        cat: "elecktrpnics",
        type: "featured",
        color: "black",
    },
    {
        Id: 9,
        Name: "product9",
        price: "67",
        image: "image/p6.webp",
        cat: "phone",
        type: "top",
        color: "blue",
    },    {
        Id: 10,
        Name: "product10",
        price: "76",
        image: "image/p7.webp",
        cat: "speaker",
        type: "top",
        color: "blue",
    },    
    {
        Id: 11,
        Name: "product11",
        price: "28",
        image: "image/p8.webp",
        cat: "speaker",
        type: "top",
        color: "blue",
    },
    {
        Id: 12,
        Name: "product12",
        price: "807",
        image: "image/p12.jpg",
        cat: "speaker",
        type: "top",
        color: "blue",
    },
    {
        Id: 13,
        Name: "product13",
        price: "961",
        image: "image/varor-laptop-1.jpg",
        cat: "laptop",
        type: "top",
        color: "red",
    },
    {
        Id: 14,
        Name: "product14",
        price: "962",
        image: "image/2.jpg",
        cat: "laptop",
        type: "top",
        color: "black",
    },
    {
        Id: 15,
        Name: "product15",
        price: "963",
        image: "image/varor-laptop-3.jpg",
        cat: "laptop",
        type: "top",
        color: "black",
    },
    {
        Id: 16,
        Name: "product16",
        price: "964",
        image: "image/varor-laptop-4.jpg",
        cat: "laptop",
        type: "featured",
        color: "black",
    },
    {
        Id: 17,
        Name: "product17",
        price: "965",
        image: "image/varor-laptop-5.jpg",
        cat: "laptop",
        type: "featured",
        color: "blue",
    },
    {
        Id: 18,
        Name: "product18",
        price: "966",
        image: "image/varor-laptop-6.jpg",
        cat: "laptop",
        type: "featured",
        color: "blue",
    },
    {
        Id: 19,
        Name: "product19",
        price: "968",
        image: "image/varor-laptop-7.jpg",
        cat: "laptop",
        type: "new",
        color: "blue",
    },
    {
        Id: 20,
        Name: "product20",
        price: "969",
        image: "image/p2.webp",
        cat: "laptop",
        type: "new",
        color: "red",
    },
    {
        Id: 21,
        Name: "product21",
        price: "965",
        image: "image/varor-tv-1.jpg",
        cat: "tv",
        type: "top",
        color: "blue",
    },
    {
        Id: 22,
        Name: "product22",
        price: "966",
        image: "image/varor-tv-2.jpg",
        cat: "tv",
        type: "featured",
        color: "blue",
    },
    {
        Id: 23,
        Name: "product23",
        price: "969",
        image: "image/varor-tv-3.png",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 24,
        Name: "product24",
        price: "965",
        image: "image/varor-tv-4.jpg",
        cat: "tv",
        type: "top",
        color: "blue",
    },
    {
        Id: 25,
        Name: "product25",
        price: "966",
        image: "image/varor-tv-5.jpg",
        cat: "tv",
        type: "featured",
        color: "blue",
    },
    {
        Id: 26,
        Name: "product26",
        price: "969",
        image: "image/varor-tv-6.jpg",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 27,
        Name: "product27",
        price: "965",
        image: "image/varor-tv-7.jpg",
        cat: "tv",
        type: "top",
        color: "blue",
    },
    {
        Id: 28,
        Name: "product28",
        price: "966",
        image: "image/varor-tv-8.jpg",
        cat: "tv",
        type: "featured",
        color: "blue",
    },
    {
        Id: 29,
        Name: "product29",
        price: "969",
        image: "image/varor-tv-9.jpg",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 30,
        Name: "product30",
        price: "96",
        image: "image/varor-tv-10.jpg",
        cat: "tv",
        type: "new",
        color: "black",
    },
    {
        Id: 31,
        Name: "product31",
        price: "965",
        image: "image/varor-speaker-1.jpg",
        cat: "speaker",
        type: "top",
        color: "blue",
    },
    {
        Id: 32,
        Name: "product32",
        price: "966",
        image: "image/p4.webp",
        cat: "speaker",
        type: "featured",
        color: "black",
    },
    {
        Id: 33,
        Name: "product33",
        price: "969",
        image: "image/varor-speaker-3.png",
        cat: "speaker",
        type: "new",
        color: "red",
    },
    {
        Id: 34,
        Name: "product34",
        price: "965",
        image: "image/varor-speaker-3.png",
        cat: "speaker",
        type: "top",
        color: "black",
    },
    {
        Id: 35,
        Name: "product35",
        price: "966",
        image: "image/varor-speaker-10.jpg",
        cat: "speaker",
        type: "featured",
        color: "blue",
    },
    {
        Id: 36,
        Name: "product36",
        price: "969",
        image: "image/varor-speaker-6.png",
        cat: "speaker",
        type: "new",
        color: "red",
    },
    {
        Id: 37,
        Name: "product37",
        price: "965",
        image: "image/varor-speaker-6.png",
        cat: "speaker",
        type: "top",
        color: "red",
    },
    {
        Id: 38,
        Name: "product38",
        price: "966",
        image: "image/varor-speaker-10.jpg",
        cat: "speaker",
        type: "featured",
        color: "red",
    },
    {
        Id: 39,
        Name: "product39",
        price: "969",
        image: "image/varor-speaker-9.jpg",
        cat: "speaker",
        type: "new",
        color: "red",
    },
    {
        Id: 40,
        Name: "product40",
        price: "96",
        image: "image/varor-speaker-10.jpg",
        cat: "speaker",
        type: "new",
        color: "black",
    },
    {
        Id: 41,
        Name: "product41",
        price: "965",
        image: "image/varor-mobile-1.png",
        cat: "phone",
        type: "top",
        color: "blue",
    },
    {
        Id: 42,
        Name: "product42",
        price: "966",
        image: "image/varor-mobile-2.jpg",
        cat: "phone",
        type: "featured",
        color: "black",
    },
    {
        Id: 43,
        Name: "product43",
        price: "969",
        image: "image/varor-mobile-3.jpg",
        cat: "phone",
        type: "new",
        color: "red",
    },
    {
        Id: 44,
        Name: "product44",
        price: "965",
        image: "image/varor-mobile-4.jpg",
        cat: "phone",
        type: "top",
        color: "black",
    },
    {
        Id: 45,
        Name: "product45",
        price: "966",
        image: "image/varor-mobile-5.jpg",
        cat: "phone",
        type: "featured",
        color: "blue",
    },
    {
        Id: 46,
        Name: "product46",
        price: "969",
        image: "image/varor-mobile-6.jpg",
        cat: "phone",
        type: "new",
        color: "red",
    },
    {
        Id: 47,
        Name: "product47",
        price: "965",
        image: "image/varor-mobile-7.jpg",
        cat: "phone",
        type: "top",
        color: "red",
    },
    {
        Id: 48,
        Name: "product48",
        price: "966",
        image: "image/varor-mobile-8.jpg",
        cat: "phone",
        type: "featured",
        color: "red",
    },
    {
        Id: 49,
        Name: "product49",
        price: "969",
        image: "image/varor-mobile-9.jpg",
        cat: "phone",
        type: "new",
        color: "red",
    },
    {
        Id: 50,
        Name: "product50",
        price: "96",
        image: "image/varor-mobile-10.jpg",
        cat: "phone",
        type: "new",
        color: "black",
    },
    {
        Id: 51,
        Name: "product51",
        price: "965",
        image: "image/varor-headphones-1.jpg",
        cat: "headphones",
        type: "top",
        color: "blue",
    },
    {
        Id: 52,
        Name: "product52",
        price: "966",
        image: "image/varor-headphones-2.jpg",
        cat: "headphones",
        type: "featured",
        color: "black",
    },
    {
        Id: 53,
        Name: "product53",
        price: "969",
        image: "image/varor-headphones-3.jpg",
        cat: "headphones",
        type: "new",
        color: "red",
    },
    {
        Id: 54,
        Name: "product54",
        price: "965",
        image: "image/varor-headphones-4.jpg",
        cat: "headphones",
        type: "top",
        color: "black",
    },
    {
        Id: 55,
        Name: "product55",
        price: "966",
        image: "image/varor-headphones-5.jpg",
        cat: "headphones",
        type: "featured",
        color: "blue",
    },
    {
        Id: 56,
        Name: "product56",
        price: "969",
        image: "image/varor-headphones-6.jpg",
        cat: "headphones",
        type: "new",
        color: "red",
    },
    {
        Id: 57,
        Name: "product57",
        price: "965",
        image: "image/varor-headphones-7.jpg",
        cat: "headphones",
        type: "top",
        color: "red",
    },
    {
        Id: 58,
        Name: "product58",
        price: "966",
        image: "image/varor-headphones-8.jpg",
        cat: "headphones",
        type: "featured",
        color: "red",
    },
    {
        Id: 59,
        Name: "product59",
        price: "969",
        image: "image/varor-headphones-9.jpg",
        cat: "headphones",
        type: "new",
        color: "red",
    },
    {
        Id: 60,
        Name: "product60",
        price: "96",
        image: "image/varor-headphones-10.jpg",
        cat: "headphones",
        type: "new",
        color: "black",
    },
    {
        Id: 61,
        Name: "product61",
        price: "965",
        image: "image/varor-watch-1.jpg",
        cat: "watch",
        type: "top",
        color: "blue",
    },
    {
        Id: 62,
        Name: "product62",
        price: "966",
        image: "image/varor-watch-2.jpg",
        cat: "watch",
        type: "featured",
        color: "black",
    },
    {
        Id: 63,
        Name: "product63",
        price: "969",
        image: "image/varor-watch-3.jpg",
        cat: "watch",
        type: "new",
        color: "red",
    },
    {
        Id: 64,
        Name: "product64",
        price: "965",
        image: "image/varor-watch-4.jpg",
        cat: "watch",
        type: "top",
        color: "black",
    },
    {
        Id: 65,
        Name: "product65",
        price: "966",
        image: "image/varor-watch-5.jpg",
        cat: "watch",
        type: "featured",
        color: "blue",
    },
    {
        Id: 66,
        Name: "product66",
        price: "969",
        image: "image/varor-watch-6.jpg",
        cat: "watch",
        type: "new",
        color: "red",
    },
    {
        Id: 67,
        Name: "product67",
        price: "965",
        image: "image/varor-watch-7.jpg",
        cat: "watch",
        type: "top",
        color: "red",
    },
    {
        Id: 68,
        Name: "product68",
        price: "966",
        image: "image/varor-watch-8.png",
        cat: "watch",
        type: "featured",
        color: "red",
    },
    {
        Id: 69,
        Name: "product69",
        price: "969",
        image: "image/varor-watch-9.png",
        cat: "watch",
        type: "new",
        color: "red",
    },
    {
        Id: 70,
        Name: "product70",
        price: "96",
        image: "image/varor-watch-10.jpg",
        cat: "watch",
        type: "new",
        color: "black",
    },





    {
        Id: 1114,
        Name: "product1114",
        price: "807",
        image: "image/S-tv-img.jpg",
        cat: "tv",
        type: "slider",
        info: "If you're in the market for a new TV, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them.",
    },
    {
        Id: 1115,
        Name: "product1115",
        price: "807",
        image: "image/S-phone-img.jpg",
        cat: "phone",
        type: "slider",
        info: "If you're in the market for a new phone, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them.",
    },
    {
        Id: 1116,
        Name: "product1116",
        price: "807",
        image: "image/S-headphones-img.jpg",
        cat: "headphones",
        type: "slider",
        info: "If you're in the market for a new headphones, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them.",
    },
    {
        Id: 1117,
        Name: "product1117",
        price: "807",
        image: "image/S-lap-img.png",
        cat: "laptop",
        type: "slider",
        info: "If you're in the market for a new laptop, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them.",
    },
    {
        Id: 1118,
        Name: "product1118",
        price: "807",
        image: "image/S-speaker-img.jpg",
        cat: "speaker",
        type: "slider",
        info: "If you're in the market for a new speaker, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them.",
    },
    {
        Id: 1119,
        Name: "product1119",
        price: "807",
        image: "image/S-clock-img.jpg",
        cat: "watch",
        type: "slider",
        info: "If you're in the market for a new watch, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them.",
    },
    {
        Id: 1120,
        Name: "product1120",
        price: "807",
        image: "image/S-all-img.png",
        cat: "all",
        type: "slider",
        info: "If you're in the market for a new watch, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them.",
    },
    
    
    
    
]
export default Homeproduct;