const Homeproduct =
[
    {
        Id: 1,
        Name: "product1",
        price: "26",
        image: "image/p1.webp",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 2,
        Name: "product2",
        price: "96",
        image: "image/p2.webp",
        cat: "laptop",
        type: "new",
        color: "red",
    },
    {
        Id: 3,
        Name: "product3",
        price: "36",
        image: "image/p3.webp",
        cat: "watch",
        type: "new",
        color: "red",
    },
    {
        Id: 4,
        Name: "product4",
        price: "636",
        image: "image/p9.jpg",
        cat: "laptop",
        type: "new",
        color: "red",
    },
    {
        Id: 5,
        Name: "product5",
        price: "46",
        image: "image/p4.webp",
        cat: "speaker",
        type: "featured",
        color: "black",
    },
    {
        Id: 6,
        Name: "product6",
        price: "56",
        image: "image/p5.webp",
        cat: "elecktrpnics",
        type: "featured",
        color: "black",
    },
    {
        Id: 7,
        Name: "product7",
        price: "956",
        image: "image/p10.jpg",
        cat: "headphone",
        type: "featured",
        color: "black",
    },
    {
        Id: 8,
        Name: "product8",
        price: "389",
        image: "image/p11.jpg",
        cat: "elecktrpnics",
        type: "featured",
        color: "black",
    },
    {
        Id: 9,
        Name: "product9",
        price: "67",
        image: "image/p6.webp",
        cat: "phone",
        type: "top",
        color: "blue",
    },    {
        Id: 10,
        Name: "product10",
        price: "76",
        image: "image/p7.webp",
        cat: "speaker",
        type: "top",
        color: "blue",
    },    
    {
        Id: 11,
        Name: "product11",
        price: "28",
        image: "image/p8.webp",
        cat: "speaker",
        type: "top",
        color: "blue",
    },
    {
        Id: 12,
        Name: "product12",
        price: "807",
        image: "image/p12.jpg",
        cat: "speaker",
        type: "top",
        color: "blue",
    },
    {
        Id: 13,
        Name: "product13",
        price: "961",
        image: "image/varor-laptop-1.jpg",
        cat: "laptop",
        type: "top",
        color: "red",
    },
    {
        Id: 14,
        Name: "product14",
        price: "962",
        image: "image/2.jpg",
        cat: "laptop",
        type: "top",
        color: "black",
    },
    {
        Id: 15,
        Name: "product15",
        price: "963",
        image: "image/varor-laptop-3.jpg",
        cat: "laptop",
        type: "top",
        color: "black",
    },
    {
        Id: 16,
        Name: "product16",
        price: "964",
        image: "image/varor-laptop-4.jpg",
        cat: "laptop",
        type: "featured",
        color: "black",
    },
    {
        Id: 17,
        Name: "product17",
        price: "965",
        image: "image/varor-laptop-5.jpg",
        cat: "laptop",
        type: "featured",
        color: "blue",
    },
    {
        Id: 18,
        Name: "product18",
        price: "966",
        image: "image/varor-laptop-6.jpg",
        cat: "laptop",
        type: "featured",
        color: "blue",
    },
    {
        Id: 19,
        Name: "product19",
        price: "968",
        image: "image/varor-laptop-7.jpg",
        cat: "laptop",
        type: "new",
        color: "blue",
    },
    {
        Id: 20,
        Name: "product20",
        price: "969",
        image: "image/p2.webp",
        cat: "laptop",
        type: "new",
        color: "red",
    },
    {
        Id: 21,
        Name: "product21",
        price: "965",
        image: "image/varor-tv-1.jpg",
        cat: "tv",
        type: "top",
        color: "blue",
    },
    {
        Id: 22,
        Name: "product22",
        price: "966",
        image: "image/varor-tv-2.jpg",
        cat: "tv",
        type: "featured",
        color: "blue",
    },
    {
        Id: 23,
        Name: "product23",
        price: "969",
        image: "image/varor-tv-3.png",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 24,
        Name: "product24",
        price: "965",
        image: "image/varor-tv-4.jpg",
        cat: "tv",
        type: "top",
        color: "blue",
    },
    {
        Id: 25,
        Name: "product25",
        price: "966",
        image: "image/varor-tv-5.jpg",
        cat: "tv",
        type: "featured",
        color: "blue",
    },
    {
        Id: 26,
        Name: "product26",
        price: "969",
        image: "image/varor-tv-6.jpg",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 27,
        Name: "product27",
        price: "965",
        image: "image/varor-tv-7.jpg",
        cat: "tv",
        type: "top",
        color: "blue",
    },
    {
        Id: 28,
        Name: "product28",
        price: "966",
        image: "image/varor-tv-8.jpg",
        cat: "tv",
        type: "featured",
        color: "blue",
    },
    {
        Id: 29,
        Name: "product29",
        price: "969",
        image: "image/varor-tv-9.jpg",
        cat: "tv",
        type: "new",
        color: "red",
    },
    {
        Id: 30,
        Name: "product30",
        price: "96",
        image: "image/varor-tv-10.jpg",
        cat: "tv",
        type: "new",
        color: "black",
    },
    // {
    //     Id: 14,
    //     Name: "product14",
    //     price: "807",
    //     image: "S-tv-img.jpg",
    //     cat: "shop",
    //     type: "slider",
    //     info: "If you're in the market for a new TV, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them. Lastly, if the price fits your budget, it might be the right choice.",
    // },
    // {
    //     Id: 15,
    //     Name: "product14",
    //     price: "807",
    //     image: "S-tv-img.jpg",
    //     cat: "",
    //     type: "slider",
    //     info: "If you're in the market for a new TV, it's essential to consider if the features match your needs. Think about if the size, resolution, and smart capabilities align with your viewing preferences. Also, if energy efficiency and connectivity options are important, ensure the TV supports them. Lastly, if the price fits your budget, it might be the right choice.",
    // }
    
    
]
export default Homeproduct;